name: Build and Test C program using CUnit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        make
        ./libftprintf.a