name: Build and Test C program using CUnit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        sudo apt-get update
        sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev
        cc *.c -o test -L/usr/local/lib -lcunit
        ./test